In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
df = pd.read_csv('train.csv')
print(df.head())

   id  Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0   0               0.0         No                      6.0            4.0
1   1               1.0         No                      7.0            3.0
2   2               6.0        Yes                      1.0            0.0
3   3               3.0         No                      7.0            3.0
4   4               1.0         No                      4.0            4.0

  Drained_after_socializing  Friends_circle_size  Post_frequency Personality
0                        No                 15.0             5.0   Extrovert
1                        No                 10.0             8.0   Extrovert
2                       NaN                  3.0             0.0   Introvert
3                        No                 11.0             5.0   Extrovert
4                        No                 13.0             NaN   Extrovert

In [58]:
df.head()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert

In [59]:
df2 = pd.read_csv('test.csv')
print(df2.head())

      id  Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0  18524               3.0         No                      7.0            4.0
1  18525               NaN        Yes                      0.0            0.0
2  18526               3.0         No                      5.0            6.0
3  18527               3.0         No                      4.0            4.0
4  18528               9.0        Yes                      1.0            2.0

  Drained_after_socializing  Friends_circle_size  Post_frequency
0                        No                  6.0             NaN
1                       Yes                  5.0             1.0
2                        No                 15.0             9.0
3                        No                  5.0             6.0
4                       Yes                  1.0             1.0

# Feature Engineering

In [60]:
# # Create the interaction feature by multiplying existing columns
df_engg = df.copy()
df_engg_test = df2.copy()
df_engg['isolation_per_friend'] =  df_engg['Time_spent_Alone']/ df_engg['Friends_circle_size'].replace(0, np.nan)  # Avoid division by zero

df_engg_test['isolation_per_friend'] =  df_engg_test['Time_spent_Alone']/ df_engg_test['Friends_circle_size'].replace(0, np.nan)  # Avoid division by zero

df_engg_test.head()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,isolation_per_friend
0,18524,3.0,No,7.0,4.0,No,6.0,NaN,0.5
1,18525,NaN,Yes,0.0,0.0,Yes,5.0,1.0,NaN
2,18526,3.0,No,5.0,6.0,No,15.0,9.0,0.2
3,18527,3.0,No,4.0,4.0,No,5.0,6.0,0.6
4,18528,9.0,Yes,1.0,2.0,Yes,1.0,1.0,9.0

In [61]:
personality = df_engg['Personality']
df_engg = df_engg.drop(columns=['Personality', 'Time_spent_Alone', 'Friends_circle_size'])
df_engg_test = df_engg_test.drop(columns=['Time_spent_Alone', 'Friends_circle_size'])
df_engg['Personality'] = personality
df_engg.head()

,id,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Post_frequency,isolation_per_friend,Personality
0,0,No,6.0,4.0,No,5.0,0.000000,Extrovert
1,1,No,7.0,3.0,No,8.0,0.100000,Extrovert
2,2,Yes,1.0,0.0,NaN,0.0,2.000000,Introvert
3,3,No,7.0,3.0,No,5.0,0.272727,Extrovert
4,4,No,4.0,4.0,No,NaN,0.076923,Extrovert

# Converting to Numpy Array

In [62]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [63]:
XX = df2.iloc[:,1:].values

In [64]:
print(X[:10])
print(y[:10])

[[0.0 'No' 6.0 4.0 'No' 15.0 5.0]
 [1.0 'No' 7.0 3.0 'No' 10.0 8.0]
 [6.0 'Yes' 1.0 0.0 nan 3.0 0.0]
 [3.0 'No' 7.0 3.0 'No' 11.0 5.0]
 [1.0 'No' 4.0 4.0 'No' 13.0 nan]
 [2.0 'No' 8.0 5.0 'No' nan 3.0]
 [1.0 'No' 8.0 nan 'No' nan 4.0]
 [2.0 'No' 8.0 3.0 'No' 4.0 5.0]
 [4.0 'Yes' 2.0 1.0 nan 0.0 2.0]
 [1.0 'No' 8.0 6.0 'No' 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']

In [65]:
print(XX[:10])

[[3.0 'No' 7.0 4.0 'No' 6.0 nan]
 [nan 'Yes' 0.0 0.0 'Yes' 5.0 1.0]
 [3.0 'No' 5.0 6.0 'No' 15.0 9.0]
 [3.0 'No' 4.0 4.0 'No' 5.0 6.0]
 [9.0 'Yes' 1.0 2.0 'Yes' 1.0 1.0]
 [2.0 'No' 5.0 3.0 'No' 10.0 4.0]
 [3.0 'No' 4.0 5.0 'No' 15.0 5.0]
 [11.0 'Yes' 2.0 1.0 'Yes' 4.0 1.0]
 [2.0 'No' 6.0 nan 'No' 9.0 6.0]
 [8.0 nan 2.0 1.0 'Yes' 1.0 1.0]]

# Imputation

In [66]:
from sklearn.impute import SimpleImputer
# Use mean imputation for numeric columns only (columns 2, 5, 6)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, [2, 5, 6]])
X[:, [2, 5, 6]] = imputer.transform(X[:, [2, 5, 6]])

In [67]:
# Use most_frequent imputation for categorical columns (columns 1, 4) and remaining numeric columns (0, 3)
imputer2 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, [0, 1, 3, 4]] = imputer2.fit_transform(X[:, [0, 1, 3, 4]])

In [68]:
# Apply same imputation to test data
# Mean imputation for numeric columns
imputer.fit(XX[:, [2, 5, 6]])
XX[:, [2, 5, 6]] = imputer.transform(XX[:, [2, 5, 6]])
# Most frequent imputation for categorical and remaining numeric columns  
XX[:, [0, 1, 3, 4]] = imputer2.fit_transform(XX[:, [0, 1, 3, 4]])

In [69]:
print(X[:10])
print(y[:10])

[[0.0 'No' 6.0 4.0 'No' 15.0 5.0]
 [1.0 'No' 7.0 3.0 'No' 10.0 8.0]
 [6.0 'Yes' 1.0 0.0 'No' 3.0 0.0]
 [3.0 'No' 7.0 3.0 'No' 11.0 5.0]
 [1.0 'No' 4.0 4.0 'No' 13.0 4.982097334878332]
 [2.0 'No' 8.0 5.0 'No' 7.996737263880939 3.0]
 [1.0 'No' 8.0 5.0 'No' 7.996737263880939 4.0]
 [2.0 'No' 8.0 3.0 'No' 4.0 5.0]
 [4.0 'Yes' 2.0 1.0 'No' 0.0 2.0]
 [1.0 'No' 8.0 6.0 'No' 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']

# Encoding

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

encoding = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [1, 4])  # Apply to categorical columns only
    ],
    remainder='passthrough'  # Keep all other columns as they are
)
X = np.array(encoding.fit_transform(X))

In [71]:
print(X[:10])
print(y[:10])

[[1.0 0.0 1.0 0.0 0.0 6.0 4.0 15.0 5.0]
 [1.0 0.0 1.0 0.0 1.0 7.0 3.0 10.0 8.0]
 [0.0 1.0 1.0 0.0 6.0 1.0 0.0 3.0 0.0]
 [1.0 0.0 1.0 0.0 3.0 7.0 3.0 11.0 5.0]
 [1.0 0.0 1.0 0.0 1.0 4.0 4.0 13.0 4.982097334878332]
 [1.0 0.0 1.0 0.0 2.0 8.0 5.0 7.996737263880939 3.0]
 [1.0 0.0 1.0 0.0 1.0 8.0 5.0 7.996737263880939 4.0]
 [1.0 0.0 1.0 0.0 2.0 8.0 3.0 4.0 5.0]
 [0.0 1.0 1.0 0.0 4.0 2.0 1.0 0.0 2.0]
 [1.0 0.0 1.0 0.0 1.0 8.0 6.0 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']

In [72]:
XX = np.array(encoding.fit_transform(XX))

In [73]:
print(XX[:10])

[[1.0 0.0 1.0 0.0 3.0 7.0 4.0 6.0 5.0289578637073005]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 5.0 1.0]
 [1.0 0.0 1.0 0.0 3.0 5.0 6.0 15.0 9.0]
 [1.0 0.0 1.0 0.0 3.0 4.0 4.0 5.0 6.0]
 [0.0 1.0 0.0 1.0 9.0 1.0 2.0 1.0 1.0]
 [1.0 0.0 1.0 0.0 2.0 5.0 3.0 10.0 4.0]
 [1.0 0.0 1.0 0.0 3.0 4.0 5.0 15.0 5.0]
 [0.0 1.0 0.0 1.0 11.0 2.0 1.0 4.0 1.0]
 [1.0 0.0 1.0 0.0 2.0 6.0 3.0 9.0 6.0]
 [1.0 0.0 0.0 1.0 8.0 2.0 1.0 1.0 1.0]]

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [75]:
print(y[:10])

[0 0 1 0 0 0 0 0 1 0]

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

# Feature Scaling

In [77]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_train_scaled[:, 4:] = scaler.fit_transform(X_train[:, 4:])
X_test_scaled = X_test.copy()
X_test_scaled[:, 4:] = scaler.transform(X_test[:, 4:])
X_scaled = X.copy()
X_scaled[:, 4:] = scaler.fit_transform(X[:, 4:])

In [78]:
XX_scaled = XX.copy()
XX_scaled[:, 4:] = scaler.transform(XX[:, 4:])

In [79]:
print(X_test_scaled[:10])

[[0.0 1.0 0.0 1.0 0.016839909908640975 -1.60131928006566
  -2.0565721047944336 -1.2161624030922265 -1.0684210579830913]
 [1.0 0.0 1.0 0.0 0.016839909908640975 1.4023072426725567
  -0.5560875387490044 0.9750518988777901 0.3643183936072774]
 [1.0 0.0 1.0 0.0 -0.3154512018572041 1.0268539273302795
  0.4442355052812819 0.4881153873288976 -0.35205133218790696]
 [1.0 0.0 1.0 0.0 -0.9800334253888943 1.4023072426725567
  0.944397027296425 -0.2422893799944413 0.006133530709685233]
 [1.0 0.0 1.0 0.0 -0.6477423136230492 1.0268539273302795
  -0.055926016733861245 0.4881153873288976 1.438872982300054]
 [1.0 0.0 1.0 0.0 -0.6477423136230492 1.0268539273302795
  1.4445585493115682 -0.4857576357688876 0.7225032565048696]
 [1.0 0.0 1.0 0.0 -0.3154512018572041 1.0268539273302795
  0.4442355052812819 1.705456666201129 -0.35205133218790696]
 [0.0 1.0 0.0 1.0 0.6814221334403311 -1.60131928006566 0.4442355052812819
  -0.7292258915433338 -1.7847907837782757]
 [1.0 0.0 1.0 0.0 -0.3154512018572041 1.4023072426725567
  0.944397027296425 1.4619884104266827 1.0806881194024618]
 [1.0 0.0 0.0 1.0 1.6782954687378666 -0.8504126493811058
  -1.5564105827792907 -1.2161624030922265 -0.0002789329424210217]]

# Class Imbalance Check

In [80]:
from collections import Counter
print(Counter(y))

Counter({0: 13699, 1: 4825})

In [81]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=0)
X_train_scaled_balanced, y_train_balanced = sm.fit_resample(X_train_scaled, y_train)
X_train_balanced, y_train_balanced = sm.fit_resample(X_train, y_train)
X_balanced, y_balanced = sm.fit_resample(X, y)
X_scaled_balanced, y_scaled_balanced = sm.fit_resample(X_scaled, y)

In [82]:
from collections import Counter
print("After SMOTE:", Counter(y_train_balanced))

After SMOTE: Counter({1: 10960, 0: 10960})

# Logistic Regression

In [83]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train_scaled_balanced, y_train_balanced)

LogisticRegression(random_state=0)

In [84]:
y_pred = classifier.predict(X_test_scaled)

In [85]:
y_pred_xx = classifier.predict(XX_scaled)

In [86]:
print(y_pred_xx[:10])
test_predictions = le.inverse_transform(y_pred_xx)
print(test_predictions[:10])

[0 1 0 0 1 0 0 1 0 1]
['Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert'
 'Extrovert' 'Introvert' 'Extrovert' 'Introvert']

In [87]:
# Assuming df2 has a column named "id" as its first column
ids = df2.iloc[:, 0]  # or df2['id'] if the column is named 'id'

# Create a new DataFrame for output
output_df = pd.DataFrame({
    'id': ids,
    'Personality': test_predictions
})

# Save to CSV
output_df.to_csv('submission.csv', index=False)

# Optional: preview the first few rows
print(output_df.head())

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

# Random Forest

In [88]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, random_state=0)
rf.fit(X_balanced, y_balanced)

RandomForestClassifier(n_estimators=300, random_state=0)

In [89]:
rf_y_pred_xx = rf.predict(XX)
print(rf_y_pred_xx[:10])

[0 1 0 0 1 0 0 1 0 1]

In [90]:
rf_test_predictions = le.inverse_transform(rf_y_pred_xx)
print(rf_test_predictions[:10])

['Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert'
 'Extrovert' 'Introvert' 'Extrovert' 'Introvert']

In [91]:
# Assuming df2 has a column named "id" as its first column
ids = df2.iloc[:, 0]  # or df2['id'] if the column is named 'id'

# Create a new DataFrame for output
output_df = pd.DataFrame({
    'id': ids,
    'Personality': rf_test_predictions
})

# Save to CSV
output_df.to_csv('rf_submission.csv', index=False)

# Optional: preview the first few rows
print(output_df.head())

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

# GridSearch Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# 1. Define your hyperparameter grid
param_grid = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# 2. Create the classifier
rf = RandomForestClassifier(random_state=42)

# 3. GridSearchCV with cross-validation (5-fold)
grid_search = GridSearchCV(estimator=rf,
                           param_grid=param_grid,
                           cv=5,            # 5-fold cross-validation
                           n_jobs=-1,       # Use all cores
                           verbose=2,
                           scoring='f1')    # You can also use 'accuracy', 'roc_auc', etc.

# 4. Fit the grid search on full data
grid_search.fit(X_balanced, y_balanced)

# 5. Show best parameters
print("Best Parameters Found:")
print(grid_search.best_params_)

# 6. Train final model on full data using best params
best_rf = RandomForestClassifier(**grid_search.best_params_, random_state=42)
best_rf.fit(X_balanced, y_balanced)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.6s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.6s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.8s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.8s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   3.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   3.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=500; total time=   7.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   3.0s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   7.2s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   6.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=500; total time=   6.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.5s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=1, min_samples_split=10, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.7s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.6s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=   2.6s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   3.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   3.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   4.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   1.4s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   6.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   7.1s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   6.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   7.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=500; total time=   7.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   3.2s

In [ ]:
rfcv_y_pred_xx = best_rf.predict(XX)
print(rfcv_y_pred_xx[:10])

[0 1 0 0 1 0 0 1 0 1]

In [ ]:
rfcv_test_predictions = le.inverse_transform(rfcv_y_pred_xx)
print(rfcv_test_predictions[:10])

['Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert'
 'Extrovert' 'Introvert' 'Extrovert' 'Introvert']

In [ ]:
# Assuming df2 has a column named "id" as its first column
ids = df2.iloc[:, 0]  # or df2['id'] if the column is named 'id'

# Create a new DataFrame for output
output_df = pd.DataFrame({
    'id': ids,
    'Personality': rfcv_test_predictions
})
# Save to CSV
output_df.to_csv('rfcv_submission.csv', index=False)

# Optional: preview the first few rows
print(output_df.head())

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

# MLP

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Train MLP Classifier
mlp_classifier = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    max_iter=500,
    learning_rate_init=0.001,
    alpha=0.0001,
    random_state=0,
    early_stopping=True,
    validation_fraction=0.1
)
mlp_classifier.fit(X_scaled_balanced, y_scaled_balanced)

# Predictions
y_pred_mlp = mlp_classifier.predict(XX_scaled)

In [ ]:
mlp_y_pred_xx = mlp_classifier.predict(XX_scaled)
print(mlp_y_pred_xx[:10])

[0 1 0 0 1 0 0 1 0 1]

In [ ]:
mlp_test_predictions = le.inverse_transform(mlp_y_pred_xx)
print(mlp_test_predictions[:10])

['Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert'
 'Extrovert' 'Introvert' 'Extrovert' 'Introvert']

In [ ]:
# Assuming df2 has a column named "id" as its first column
ids = df2.iloc[:, 0]  # or df2['id'] if the column is named 'id'

# Create a new DataFrame for output
output_df = pd.DataFrame({
    'id': ids,
    'Personality': mlp_test_predictions
})
# Save to CSV
output_df.to_csv('mlp_submission.csv', index=False)

# Optional: preview the first few rows
print(output_df.head())

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert